"""init

Revision ID: c3ee79a2a3f6
Revises: 
Create Date: 2026-05-15 09:24:16.041456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3ee79a2a3f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('auth_level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('token', table_name='api_auth')
    op.drop_table('api_auth')
    op.drop_table('api_call_log')
    op.drop_index('idx_func_type', table_name='func_ai_index')
    op.drop_index('idx_is_safe', table_name='func_ai_index')
    op.drop_index('uk_func_id', table_name='func_ai_index')
    op.drop_table('func_ai_index')
    op.alter_column('func_audit', 'audit_status',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('func_audit', 'audit_user',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('func_audit', 'audit_remark',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_func_audit_id'), 'func_audit', ['id'], unique=False)
    op.create_foreign_key(None, 'func_audit', 'func_base', ['func_id'], ['id'])
    op.alter_column('func_base', 'func_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('func_base', 'func_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('func_base', 'func_params',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('func_base', 'func_return',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_func_base_func_type'), 'func_base', ['func_type'], unique=False)
    op.create_index(op.f('ix_func_base_id'), 'func_base', ['id'], unique=False)
    op.alter_column('func_category', 'category_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('func_category', 'func_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('func_category', 'category_desc',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_func_category_func_type'), 'func_category', ['func_type'], unique=False)
    op.create_index(op.f('ix_func_category_id'), 'func_category', ['id'], unique=False)
    op.create_index(op.f('ix_func_category_relation_id'), 'func_category_relation', ['id'], unique=False)
    op.create_foreign_key(None, 'func_category_relation', 'func_base', ['func_id'], ['id'])
    op.create_foreign_key(None, 'func_category_relation', 'func_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'func_category_relation', type_='foreignkey')
    op.drop_constraint(None, 'func_category_relation', type_='foreignkey')
    op.drop_index(op.f('ix_func_category_relation_id'), table_name='func_category_relation')
    op.drop_index(op.f('ix_func_category_id'), table_name='func_category')
    op.drop_index(op.f('ix_func_category_func_type'), table_name='func_category')
    op.alter_column('func_category', 'category_desc',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=True)
    op.alter_column('func_category', 'func_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
    op.alter_column('func_category', 'category_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_func_base_id'), table_name='func_base')
    op.drop_index(op.f('ix_func_base_func_type'), table_name='func_base')
    op.alter_column('func_base', 'func_return',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=True)
    op.alter_column('func_base', 'func_params',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('func_base', 'func_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.alter_column('func_base', 'func_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'func_audit', type_='foreignkey')
    op.drop_index(op.f('ix_func_audit_id'), table_name='func_audit')
    op.alter_column('func_audit', 'audit_remark',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=True)
    op.alter_column('func_audit', 'audit_user',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    op.alter_column('func_audit', 'audit_status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_table('func_ai_index',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('func_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('func_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('func_intro', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('func_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('is_safe', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uk_func_id', 'func_ai_index', ['func_id'], unique=False)
    op.create_index('idx_is_safe', 'func_ai_index', ['is_safe'], unique=False)
    op.create_index('idx_func_type', 'func_ai_index', ['func_type'], unique=False)
    op.create_table('api_call_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('caller_ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('caller_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('func_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('call_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('call_status', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('call_msg', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('api_auth',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('auth_level', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('expire_time', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index('token', 'api_auth', ['token'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
